/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/H53jpYG7PcI
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"

export function ReviewBox() {
  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      <Card>
        <div className="aspect-card overflow-hidden rounded-lg">
          <img alt="Image" className="aspect-item object-top" height="1" src="/placeholder.svg" width="1" />
        </div>
        <CardHeader className="p-4">
          <CardTitle className="text-lg font-medium">Restaurant Name</CardTitle>
          <CardDescription className="text-sm truncate">Italian cuisine, pasta & pizza</CardDescription>
        </CardHeader>
        <CardContent className="p-4 grid gap-2">
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.5
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.0
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            4.7
          </div>
        </CardContent>
        <CardFooter className="p-4">
          <Link className="text-sm font-medium underline" href="#" target="_blank">
            View on Google Maps
          </Link>
        </CardFooter>
      </Card>
      <Card>
        <div className="aspect-card overflow-hidden rounded-lg">
          <img alt="Image" className="aspect-item object-top" height="1" src="/placeholder.svg" width="1" />
        </div>
        <CardHeader className="p-4">
          <CardTitle className="text-lg font-medium">Coffee Shop</CardTitle>
          <CardDescription className="text-sm truncate">Best coffee in town</CardDescription>
        </CardHeader>
        <CardContent className="p-4 grid gap-2">
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.5
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.0
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            4.7
          </div>
        </CardContent>
        <CardFooter className="p-4">
          <Link className="text-sm font-medium underline" href="#" target="_blank">
            View on Google Maps
          </Link>
        </CardFooter>
      </Card>
      <Card>
        <div className="aspect-card overflow-hidden rounded-lg">
          <img alt="Image" className="aspect-item object-top" height="1" src="/placeholder.svg" width="1" />
        </div>
        <CardHeader className="p-4">
          <CardTitle className="text-lg font-medium">Boutique Hotel</CardTitle>
          <CardDescription className="text-sm truncate">Luxury accommodation</CardDescription>
        </CardHeader>
        <CardContent className="p-4 grid gap-2">
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.5
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.0
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            4.7
          </div>
        </CardContent>
        <CardFooter className="p-4">
          <Link className="text-sm font-medium underline" href="#" target="_blank">
            View on Google Maps
          </Link>
        </CardFooter>
      </Card>
      <Card>
        <div className="aspect-card overflow-hidden rounded-lg">
          <img alt="Image" className="aspect-item object-top" height="1" src="/placeholder.svg" width="1" />
        </div>
        <CardHeader className="p-4">
          <CardTitle className="text-lg font-medium">Local Attractions</CardTitle>
          <CardDescription className="text-sm truncate">Family fun, theme park</CardDescription>
        </CardHeader>
        <CardContent className="p-4 grid gap-2">
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.5
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill" />
            <StarIcon className="w-4 h-4 fill" />
            4.0
          </div>
          <div className="flex items-center gap-2">
            <StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            <StarIcon className="w-4 h-4 fill_primary" />
            4.7
          </div>
        </CardContent>
        <CardFooter className="p-4">
          <Link className="text-sm font-medium underline" href="#" target="_blank">
            View on Google Maps
          </Link>
        </CardFooter>
      </Card>
    </div>
  )
}

interface StarIconProps {
  // Define the types for the props
  // For example:
  width?: string; // width is optional and can be a string
  height?: string; // height is optional and can be a string
  fill?: string; // fill color is optional and can be a string
  // Add more props as needed
}

function StarIcon(props: StarIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
